name:                LEC
version:             0.1.0.0
github:              "github.com/Average-user"
license:             MIT
author:              "Lucas Polymeris"
maintainer:          "lucaspoymeris@protonmail.com"
copyright:           "2018 Lucas Polymeris"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/Average-user>

dependencies:
- base >= 4.7 && < 5
- parsec == 3.1.13.0
- rainbow

library:
  source-dirs: src

executables:
  LEC-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - LEC

tests:
  LEC-test:
    main:                Tests.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - LEC
    - mtl == 2.2.2
    - QuickCheck == 2.10.1
    - hspec == 2.4.8
